### ISSUE TITLE
im not sure how to edit a unit file?

### ISSUE THREAD

**Issue by JackDinn** [isd-project/isd#42]
It all seems to be working and I thought it might be a handy app, but I can't even figure out how to edit a unit file? If I use the hotkey to "open in editor," it opens what is in the bottom window rather than the unit file itself. I thought maybe if I go to the "cat" tab and try to edit that, but I don't think it will edit and save the unit file either. I tried the system action and "systemctl edit," but then I remembered that it just creates a drop-in, not what I was looking for.

So am i supposed to still manually edit unit files? 

Ok, so I try just using Ctrl-X to copy the unit path into the clipboard and manually edit the unit. However, although a little pop-up comes up saying it has been copied to the clipboard, it has not. The clipboard is empty, so I'd have to do the path manually as well.

I don't get what the benefit is?

How do i just edit a unit file?

Its probably just my ignorance as i am pretty new to systemd.

**Comment by isd-project** [comment]
So your goal is to edit the unit file and _not_ create a drop-in?

You can think of this tool like a "fancy wrapper" around `systemctl` (and partially `journalctl`).
So you should ask yourself: What `systemctl`  command am I looking for?

So let's have a quick look at: `man systemctl`

> edit UNIT...
>           Edit or replace a drop-in snippet or the main unit file, to extend or override the definition of the specified unit. 
> [...]
> If `--full` is specified, a replacement for the main unit file will be created or edited. Otherwise, a drop-in file will be created or edited.

Aha! So you are looking for the command `systemctl edit --full <unit-name>` (and you want to make sure to set `$EDITOR` correctly).

As you have already seen, there is no such option as `systemctl edit --full`.
But `isd` is advertised as _fully configurable

So let's have a look at the [Customization](https://isd-project.github.io/isd/customization/#systemctl-keybindings) section, specifically the `systemctl` Keybindigs:

> # List of configurable systemctl subcommand keybindings.

And here you can see the _configurable_ list!
TL;DR Create a file called `~/.config/isd/config.yaml` with:

```yaml

# List of configurable systemctl subcommand keybindings.
# The exact subcommand (including arguments) can be defined by setting `command`.
# The `modal_keybinding`s provide the shortcut key(s)
# for the modal action window.
# Optionally, `direct_keybinding`s can be configured to
# immediately trigger the systemctl action from the main screen
# without having to open the modal first.
# 
# The description is used to describe the subcommand
# in the `CommandPalette`
systemctl_commands: 
  - command: "start"
    modal_keybinding: "a"
    direct_keybinding: null
    description: "Start unit(s)"
  - command: "stop"
    modal_keybinding: "o"
    direct_keybinding: "ctrl+s"
    description: "Stop unit(s)"
  - command: "restart"
    modal_keybinding: "s"
    direct_keybinding: null
    description: "Restart unit(s)"
  - command: "edit"
    modal_keybinding: "e"
    direct_keybinding: null
    description: "Edit unit(s) with configured editor"
  - command: "edit --runtime"
    modal_keybinding: "r"
    direct_keybinding: null
    description: "Edit unit(s) only for current runtime"
  - command: "reload"
    modal_keybinding: "d"
    direct_keybinding: null
    description: "Reload unit(s)"
  - command: "enable"
    modal_keybinding: "n"
    direct_keybinding: null
    description: "Enable unit(s)"
  - command: "mask"
    modal_keybinding: "m"
    direct_keybinding: null
    description: "Mask/Disable starting unit(s)"
  - command: "unmask"
    modal_keybinding: "u"
    direct_keybinding: null
    description: "Undo masking of unit(s)"
 - command: "edit --full"
   modal_keybinding: "f"
   description: "Edit unit file directly without creating a drop-in"
``` 

Where the last entry is your new command :tada:

PS: I know that this is a bit hidden atm. Whenever, I have a bit of time, I will create a `Tutorial` section for the documentation and this would be tutorial Nr. 1 ;)
